~Config
WarpSystem:
  Language: ENG
  Maintenance: false
  Admin:
    Permission: WarpSystem.Admin

  GUI:
    #false: The WarpGUI is identical on the entire server in all worlds
    #true: The WarpGUI is different in every world
    Bound_to_world: false
    Admin:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'
    User:
      #The number must be between inclusive 9 and inclusive 54 and must be divisible by 9.
      Size: 54
      Title:
        Standard: '&c&nWarps&r'
        In_Category: '&c&nWarps&r &c@%PAGE%'

  Economy:
    #Priority list for economy systems
    priority:
    - Essentials
    - Vault

  Teleport:
    Chunk_Pre_Loading:
      #If enabled, only players with the "WarpSystem.Teleport.ChunkPreLoading" will preload chunks!
      Limit_by_Permission: false
      Enabled: true
      Chunk_Radius: 1
    Animation_After_Teleport:
      Enabled: true
    Delay: 3
    Allow_Move: true

  Send:
    Teleport_Message:
      WarpGUI: true
      SimpleWarps: true
      GlobalWarps: true
      NativePortals: true
      Portals: true
      WarpSigns: true
      CommandBlocks: true
      PlayerWarps: true
    Teleport_Cancel_Message: true

  Functions:
    WarpGUI: true
    SimpleWarps: true
    EffectPortals: true
    NativePortals: true
    WarpSigns: true
    GlobalWarps: true
    Shortcuts: true
    #Available commands: '/warp <warp>' or '/globalwarp <warp>'
    #Required for '/tp' command for CommandBlocks (CommandBlocks with tp commands inside don't work, if you turn this to false)
    CommandBlocks: true
    RandomTeleports: true
    TeleportCommand: true
    PlayerWarps: true

  #'TeleportCommand' in 'Functions' (above) have to be toggled to true as well, if you want to use this feature.
  TeleportCommands:
    Back:
      #Amount of temp. saved locations for the /back command
      History_Size: 3
      Enabled: true
    Tp: true
    TpAll: true
    TpToggle: true
    Tpa: true
    TpaHere: true
    TpaAll: true
    TpaToggle: true
    #Tpa, TpaHere& TpaAll: |true: Players on this server can receive/send teleport requests from/to other servers. |false: Players can only send TeleportRequests to players on this server
    #TpAll: Only players from servers with 'BungeeCord: true' will be teleported to you.
    BungeeCord: true
    TeleportRequests:
      #Teleport costs for a transportation via tpa or tpaHere; The teleported player has to pay
      Teleport_Costs: 0
      #In seconds
      ExpireDelay: 30
      #true: The teleport request SENDER will be notified about every accepted or denied teleport request. |false: The teleport request SENDER won't get any accept or deny messages
      Notify_TpaAll_Sender: true

  EffectPortals:
    #Max distance between particle and player - Don't use distances higher than 200! It will cause lags.
    ParticleDistance: 70.0

  SimpleWarps:
    #Adds on every created warp the standard permission: 'WarpSystem.Warps.<WarpName>'
    Add_Permission_On_Creation: false

  Commands:
    Warp:
      #true: '/warp' opens the WarpGUI
      #false: '/warp <warp>' teleports you to warps
      GUI: false

  PlayerWarps:
    General:
      Support:
        #If enabled, the player can't create PlayerWarps in regions, where he cannot build
        ProtectedRegions: true
      BungeeCord: true
      #Disables all types of costs, active time selector, teleport costs
      Economy: false
      #The item of PlayerWarp is automatically the head of its owner and cannot be changed
      Force_Player_Head: false
      Custom_teleport_costs: true
      #Turn this to true, if you want, that all PlayerWarps should be public when you create them. The state can always be changed.
      Public_as_create_state: false
      PlayerWarps_Command_Aliases:
        - 'pwarps'
        - 'pws'
      PlayerWarp_Command_Aliases:
        - 'pwarp'
        - 'pw'
      Command_References:
      - 'tempwarps'
      - 'twarps'
      - 'tws'
      - 'tempwarp'
      - 'twarp'
      - 'tw'
      - 'home'
      - 'homes'
      Name_Blacklist: []
      Categories:
        Enabled: true
        Min: 0
        Max: 2
        #The IDs must be identical on every Spigot server.
        Classes:
        - Type: EMERALD
          Lore:
            - '&7This class marks a warp'
            - '&7as a &aShop&7!'
          Name: '&a&lShop'
          id: 1
        - Type: OAK_DOOR
          Lore:
            - '&7This class marks a warp'
            - '&7as a &cHome&7!'
          Name: '&c&lHome'
          id: 2
        - Type: FARMLAND
          Lore:
            - '&7This class marks a warp'
            - '&7as a &9Farm&7!'
          Name: '&9&lFarm'
          id: 3
        - Type: IRON_SWORD
          Lore:
            - '&7This class marks a warp'
            - '&7as a &ePvP-Zone&7!'
          Name: '&e&lPvP-Zone'
          id: 4
        - Type: BOW
          Lore:
            - '&7This class marks a warp'
            - '&7as a &bHunting-Area&7!'
          Name: '&b&lHunting-Area'
          id: 5
        - Type: ENDER_EYE
          Lore:
            - '&7This class marks a warp'
            - '&7as a &3miscellaneous &7warp!'
          Name: '&3&lMiscellaneous'
          id: 6
    #Time format: "0d, 0h, 0m, 0s" - Unnecessary values can be removed (examples: "1d, 5m", "10s", "5h")!
    Time:
      Min_Time: 0d, 0h, 5m
      Max_Time: 30d, 0h, 0m
    Inactive:
      #Time after an expiration. After that time, the PlayerWarp will be deleted. Inactive PlayerWarps cannot be used for teleportation purposes.
      #IMPORTANT: If BungeeCord is enabled, you have to set this value in the Config.yml in the WarpSystem folder on your BungeeCord!! (It will be ignored here.)
      Time_After_Expiration: 1d, 0h, 0m
      #Time to remind a player, if a PlayerWarp is going to be deleted (already inactive)
      Reminds:
      - 12h
      - 6h
      - 1h
      - 30m
      - 15m
      - 5m
      - 3m
      - 2m
      - 1m
    Costs:
      #Factor calculation: (time left / time from born to expiration) > decreases proportionally to the remaining PlayerWarp time - factor decreases with rising "from born to expiration"-time
      Internal_Refund_Factor: false
      Round_costs_to_natural_numbers: false
      Create: 200
      Edit: 0
      PublicWarp: 100
      Personal_Item: 200
      #Costs per minute
      Active_Time: 0.5
      #Multiplicated with custom TeleportCosts - e.g. set PlayerWarp teleport fee to 100 > Costs: 100 * 25 = 2500
      Teleport_Fee: 25
      Trusted_Member: 50
      Editing:
        #Costs for editing existing values
        Name: 400
        Target_Position: 200
        Personal_Item: 100
      Text:
        #Costs per character
        Teleport_Message: 2
        Warp_Description: 2
    Name_Length:
      Min: 3
      Max: 20
    Teleport_Message:
      Length:
        Min: 5
        Max: 50
    Warp_Description:
      Max_Lines: 3
      Line_Length:
        Min: 5
        Max: 35
    Teleport_Fee:
      #Custom PlayerWarp teleport fee
      Max: 500
    Refunds:
      #Values in % (e.g. 1 = 100%, 0.25 = 25%)
      Personal_Item: 0.5
      Warp_Description: 0.5
      Teleport_Message: 0.5
      PublicWarp: 0.5
      Teleport_Fee: 0.5
      Active_Time: 1
      Trusted_Member: 0.5
    #Info that every player can only create max 2 warps
    Hide_Limit_Info: false

  #The standard and max amount of random teleports will be configured with permissions:
  #"warpsystem.randomteleporters.free.1" » This permissions means, that the player with that permission has a standard amount of 1 free random teleports
  #"warpsystem.randomteleporters.max.2" » This permissions means, that the player with that permission has a max amount of 2 random teleports, so he could buy one, if it's enabled
  RandomTeleport:
    #Costs for one extra teleport (buyable with commands)
    Buyable:
      Enabled: true
      Costs: 500
    Range:
      #Don't use too high y values! It would cause lags!!
      Highest_Y:
        Nether: 126
        End: 80
      Min: 1000
      Max: 10000
    Worlds:
      # Premium feature - Random world list won't be supported even it's set to 'true'
      Enabled: false
      #If enabled: Plugin selects a random world of this list for a random teleport
      List:
      - World
      - World_Nether
      - World_End
    Support:
      #If enabled, the player will be teleported to a random position, which is not in a protected region
      ProtectedRegions: true
      # If enabled, the player will be teleported to a random position, which is inside of the WorldBorder
      # Premium feature - WorldBorder won't be supported even it's set to 'true'
      WorldBorder: true
      #If enabled, the player will be teleported to a random position, in one of the listed biomes
      Biome:
        Enabled: false
        #Names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html
        BiomeList:
        - OCEAN
        - PLAINS
        - DESERT
        - EXTREME_HILLS
        - FOREST
        - TAIGA
        - SWAMPLAND
        - RIVER
        - HELL
        - SKY
        - FROZEN_OCEAN
        - FROZEN_RIVER
        - ICE_FLATS
        - ICE_MOUNTAINS
        - MUSHROOM_ISLAND
        - MUSHROOM_ISLAND_SHORE
        - BEACHES
        - DESERT_HILLS
        - FOREST_HILLS
        - TAIGA_HILLS
        - SMALLER_EXTREME_HILLS
        - JUNGLE
        - JUNGLE_HILLS
        - JUNGLE_EDGE
        - DEEP_OCEAN
        - STONE_BEACH
        - COLD_BEACH
        - BIRCH_FOREST
        - BIRCH_FOREST_HILLS
        - ROOFED_FOREST
        - TAIGA_COLD
        - TAIGA_COLD_HILLS
        - REDWOOD_TAIGA
        - REDWOOD_TAIGA_HILLS
        - EXTREME_HILLS_WITH_TREES
        - SAVANNA
        - SAVANNA_ROCK
        - MESA
        - MESA_ROCK
        - MESA_CLEAR_ROCK

Do_Not_Edit:
  Last_Version: "0"
