name: WarpSystem
author: CodingAir
version: '4.2.1'
description: WarpSystem
main: de.codingair.warpsystem.spigot.base.WarpSystem
softdepend: [Multiverse-Core, Vault, Essentials, MultiWorld, PlaceholderAPI]
api-version: "1.13"