WarpSystem:
  Language: ENG
  PlayerWarps:
    Inactive:
      #Time after an expiration. After that time, the PlayerWarp will be deleted.
      #Inactive PlayerWarps cannot be used for teleportation purposes.
      Time_After_Expiration: 1d, 0h, 0m